apiVersion: v1
kind: Namespace
metadata:
  name: secretscanner-system
  labels:
    app.kubernetes.io/name: secretscanner-k8s
    app.kubernetes.io/part-of: secretscanner-k8s
    pod-security.kubernetes.io/enforce: restricted
