apiVersion: v1
kind: Secret
metadata:
  name: secretscanner-webhook-tls
  namespace: secretscanner-system
  labels:
    app.kubernetes.io/name: secretscanner-webhook
    app.kubernetes.io/part-of: secretscanner-k8s
type: kubernetes.io/tls
data:
  tls.crt: "<REMOVED>"
  tls.key: "<REMOVED>"
