apiVersion: v1
kind: Service
metadata:
  name: secretscanner-webhook
  namespace: secretscanner-system
  labels:
    app.kubernetes.io/name: secretscanner-webhook
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/part-of: secretscanner-k8s
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app.kubernetes.io/name: secretscanner-webhook
